version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run: '[ "${CIRCLE_BRANCH}" == "master" ] || docker build .'
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              IMAGE_TAG=urbas/grafana-build-image:1.0.0
              docker login --username $DOCKER_USER --password $DOCKER_PASS
              docker build --tag $IMAGE_TAG .
              docker push $IMAGE_TAG
            fi
