version: 2
jobs:
  build:
    working_directory: /build
    docker:
      - image: docker:17.09.0-ce
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build - < Dockerfile